---
  title: "Explanation Valence: Cost of Intervention"
author: "Lara Kirfel"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  bookdown::html_document2:
  toc: true
toc_depth: 4
theme: cosmo
highlight: tango
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")
```

# Install packages

```{r, message=FALSE}
install.packages("reshape")
install.packages("janitor")
install.packages("DT")
install.packages("Hmisc")
install.packages("broom")
install.packages("tidyverse")
install.packages("MuMIn")
install.packages("pwr") 
install.packages("simr")
install.packages("Publish")
install.packages("ggpubr")
install.packages("emmeans")
```

```{r, message=FALSE}
library("reshape") # variety of methods for reshaping data prior 
library("janitor") # for cleaning variable names 
library("DT") # for nice tables
library("Hmisc") # for smean function for bootstrapped confidence intervals 
library("tidyverse") # for data wrangling, visualization, etc. 
library("lme4") # for fitting and analyzing mixed models
library("MuMIn") # for calculating effect sizes
library("pwr") #for power analysis 
library("simr") # for power analysis 
library("ggpubr") # for publication Ready Plots
library("emmeans") # for post hoc tests
library("brms")        # for Bayesian regression modeling
library("tidybayes")   # for Bayesian regression modeling

```

```{r}
# set ggplot theme 
theme_set(
  theme_classic()
)
```

## Experiment 4: Read in Data

```{r}
###Experiment 10
#### Read in Data

df.responses = read.csv(file = "costintervention_2-responses.csv", stringsAsFactors = F, sep = ",") %>% 
      select(-error)


df.participants <- read.csv(file = "costintervention_2-participants.csv", stringsAsFactors = F, sep = ",") %>% 
    select(-c(proliferate.condition, error))


df.data10 <- merge(df.responses, df.participants, by="workerid") 
```

## Experiment 4: Wrangle Data

```{r}
df.exp10 <- df.data10 %>% 
   gather("index", "response", -c(workerid, proliferate.condition, age, ethnicity, gender, feedback, race))%>% 
  mutate(CausalStructure  =
           case_when(
       str_detect(proliferate.condition, "Condition_1") ~ "Conjunctive",
       str_detect(proliferate.condition, "Condition_2") ~ "Disjunctive",
       str_detect(proliferate.condition, "Condition_4") ~ "Disjunctive",
       str_detect(proliferate.condition, "Condition_3") ~ "Conjunctive"))%>% 
  mutate(response  =
           case_when(
           (str_detect(proliferate.condition, "Condition_1") | str_detect(proliferate.condition, "Condition_2")) & 
             str_detect(response, "blue") ~ "cheap",
           (str_detect(proliferate.condition, "Condition_1") | str_detect(proliferate.condition, "Condition_2")) & 
             str_detect(response, "orange") ~ "expensive",
                     (str_detect(proliferate.condition, "Condition_3") | str_detect(proliferate.condition, "Condition_4")) & 
             str_detect(response, "blue") ~ "expensive",
           (str_detect(proliferate.condition, "Condition_3") | str_detect(proliferate.condition, "Condition_4")) & 
             str_detect(response, "orange") ~ "cheap",
           TRUE ~ response)) %>% 
 mutate(ResponseType =
           case_when(
       str_detect(index, "explanation") ~ "explanation",
       str_detect(index, "intervention")  ~ "intervention"))%>% 
  select(-index) %>% 
  spread(ResponseType, response) %>% 
  mutate(CausalStructure= factor(CausalStructure, levels=c("Conjunctive", "Disjunctive"))) %>%
  mutate(cheap_explanation =
           case_when(
        explanation == "cheap" ~ "cheap",
        explanation != "cheap"~ "other")) %>% 
  mutate(expensive_explanation =
           case_when(
        explanation == "expensive" ~ "expensive",
        explanation != "expensive"~ "other")) %>% 
  mutate(nopreference_explanation =
           case_when(
        explanation == "no preference" ~ "no preference",
        explanation != "no preference"~ "other")) %>% 
  mutate(cheap_intervention =
           case_when(
        intervention== "cheap" ~ "cheap",
        intervention!= "cheap"~ "other")) %>% 
  mutate(expensive_intervention  =
           case_when(
        intervention  == "expensive" ~ "expensive",
        intervention  != "expensive"~ "other")) %>% 
  mutate(nopreference_intervention  =
           case_when(
        intervention== "no preference" ~ "no preference",
        intervention!= "no preference"~ "other")) 
  

```



### Figures
```{r}
#### Set Theme
myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 16),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 16),
                   legend.text = element_text(color="black", size = 12),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"),
                  # legend.title = element_blank()
)


```






#### Explanation

```{r}

FigExplanation<-df.exp10 %>% 
  ggplot(aes(x=explanation, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of  intervention responses") +
  #facet_wrap(~CausalStructure)+
  facet_grid(~proliferate.condition)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14), 
  strip.text = element_text(color="black", size = 12)) 


FigExplanation

FigExplanations <- ggplot(df.exp10, aes(x = explanation)) +
  geom_bar(aes(y = ..prop.., fill = factor(..x..), group = 1), stat = "count") + 
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.20)) +
  ylab("proportion of explanation responses") +
  facet_wrap(~CausalStructure)+
  theme_bw() +
  theme(legend.position = "none") +
  theme(
    axis.text.x = element_text(angle = 20, hjust = 1, color = "black", size = 14), 
    strip.text = element_text(color = "black", size = 12)
  )

print(FigExplanations)
```
## Intervention

```{r}

#df.exp2subset<-df.exp2 %>% 
# filter(Order == "disjunctive first") 

FigIntervention<-df.exp10 %>% 
  ggplot(aes(x=intervention, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..), group = 1), stat = "count") + 
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.20)) +
  ylab("proportion of intervention responses") +
  facet_wrap(~CausalStructure)+
  theme_bw() +
  theme(legend.position = "none") +
  theme(
    axis.text.x = element_text(angle = 20, hjust = 1, color = "black", size = 14), 
    strip.text = element_text(color = "black", size = 12)
  )



FigIntervention
```

### Analyses
# Contrasts
```{r}
contrasts(df.exp2$CausalStructure) = contr.sum(2)
```

# Abnormal Explanation Selection
```{r}
##################### Analysis
install.packages("ggeffects")
library("ggeffects")   # for marginal effects 

fit_abnormal_explanation = brm(formula = abnormal_explanation ~ CausalStructure + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp2 %>% 
                              mutate(abnormal_explanation = ifelse(abnormal_explanation == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_abnormal_explanation

fit_abnormal_selection %>% 
  ggpredict(terms = c("CausalStructure", "Outcome"))


FreqAbnormal<-ggplot(df.exp1, aes(x=abnormal_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqAbnormal
ggsave(FreqAbnormal, file="FreqAbnormal.png", dpi=400, height = 5, width = 8)

```
# Normal Selection
```{r}
##################### Analysis

fit_normal_explanation = brm(formula = normal_explanation  ~ CausalStructure + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp2 %>% 
                              mutate(normal_explanation  = ifelse(normal_explanation  == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_normal_explanation 


FreqNormal<-ggplot(df.exp1, aes(x=normal_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqNormal
ggsave(FreqNormal, file="FreqNormal.png", dpi=400, height = 5, width = 8)

```

# No preference Selection
```{r}
##################### Analysis

fit_nopreference_explanation = brm(formula = nopreference_explanation ~ CausalStructure + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp2 %>% 
                              mutate(nopreference_explanation = ifelse(nopreference_explanation == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_nopreference_explanation


FreqNopreference<-ggplot(df.exp1, aes(x=nopreference_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqNopreference
ggsave(FreqNopreference, file="FreqNopreference.png", dpi=400, height = 5, width = 8)

```



## Plotting Explanation Selections

```{r}
FreqExp1<-ggplot(df.exp1, aes(x=response, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqExp1

plot(FreqExp1)
ggsave(FreqExp1, file="FreqExp1.png", dpi=400, height = 5, width = 8)
```

### SUBSET

```{r}
df.exp1_subset <- df.exp1 %>% 
  filter(index=="response_2") 


FreqExp1_sub<-ggplot(df.exp1_subset, aes(x=response, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqExp1_sub

plot(FreqExp1_sub)
ggsave(FreqExp1_sub, file="FreqExp1_sub.png", dpi=400, height = 5, width = 8)
```
```{r}
df.data.1_subset <- df.data1 %>% 
  filter(response_1==response_2) 
```

# Abnormal Intervention Selection
```{r}
##################### Analysis
install.packages("ggeffects")
library("ggeffects")   # for marginal effects 

fit_abnormal_intervention = brm(formula = abnormal_intervention ~ CausalStructure + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp1 %>% 
                              mutate(abnormal_intervention = ifelse(abnormal_intervention == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_abnormal_intervention

fit_abnormal_selection %>% 
  ggpredict(terms = c("CausalStructure", "Outcome"))


FreqAbnormal<-ggplot(df.exp1, aes(x=abnormal_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqAbnormal
ggsave(FreqAbnormal, file="FreqAbnormal.png", dpi=400, height = 5, width = 8)

```
# Normal Selection
```{r}
##################### Analysis

fit_normal_intervention = brm(formula = normal_intervention  ~ CausalStructure + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp1 %>% 
                              mutate(normal_intervention  = ifelse(normal_intervention  == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_normal_intervention


FreqNormal<-ggplot(df.exp1, aes(x=normal_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqNormal
ggsave(FreqNormal, file="FreqNormal.png", dpi=400, height = 5, width = 8)

```

# No preference Selection
```{r}
##################### Analysis

fit_nopreference_intervention = brm(formula = nopreference_intervention ~ CausalStructure + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp1 %>% 
                              mutate(nopreference_intervention = ifelse(nopreference_intervention == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_nopreference_intervention


FreqNopreference<-ggplot(df.exp1, aes(x=nopreference_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqNopreference
ggsave(FreqNopreference, file="FreqNopreference.png", dpi=400, height = 5, width = 8)

```


```{r}
df.exp2b <- df.data2 %>% 
    select(-c(workerid, age, ethnicity, gender, feedback, race))%>% 
mutate(explanation_conjunctive = 
         case_when(
       str_detect(proliferate.condition, "Conneg_") ~explanation_response_1,
        str_detect(proliferate.condition, "Disneg_") ~explanation_response_2)) %>% 
  mutate(explanation_disjunctive = 
         case_when(
       str_detect(proliferate.condition, "Conneg_") ~explanation_response_2,
        str_detect(proliferate.condition, "Disneg_") ~explanation_response_1)) %>% 
  mutate(intervention_conjunctive = 
         case_when(
       str_detect(proliferate.condition, "Conneg_") ~intervention_response_1,
        str_detect(proliferate.condition, "Disneg_") ~ intervention_response_2)) %>% 
  mutate(intervention_disjunctive = 
         case_when(
       str_detect(proliferate.condition, "Conneg_") ~ intervention_response_2,
        str_detect(proliferate.condition, "Disneg_") ~ intervention_response_1))



df.summary<-df.exp2b%>% 
  group_by(explanation_conjunctive, intervention_conjunctive, explanation_disjunctive, intervention_disjunctive) %>% 
  summarize(n = n()) %>% 
  mutate(percentage =n/99)

```



```{r}
df.summary<-df.exp2%>% 
  group_by(CausalStructure) %>% 
  summarize(same = sum(explanation == intervention))

df.summary<-df.exp2%>% 
  spread(CausalStructure, explanation)
  summarize(same = sum(explanation == explanation))


df.summary<-df.data2%>% 
    summarize(same_exp = sum(explanation_response_1 == explanation_response_2),
              same_int = sum(intervention_response_1 == intervention_response_2))

  sum(explanation == intervention)


sum(df.responses$explanation_response_2 == df.responses$intervention_response_2)

sum(df.responses$intervention_response_1 == df.responses$intervention_response_2)
sum(df.responses$explanation_response_1 == df.responses$explanation_response_2)



```
