---
title: "Study 2"
output: html_document
date: '2023-02-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
  title: "Explanation Valence Pilot 1: Conj/Disj Positive"
author: "Lara Kirfel"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  bookdown::html_document2:
  toc: true
toc_depth: 4
theme: cosmo
highlight: tango
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")
```

# Install packages

```{r, message=FALSE}
install.packages("reshape")
install.packages("janitor")
install.packages("DT")
install.packages("Hmisc")
install.packages("broom")
install.packages("tidyverse")
install.packages("MuMIn")
install.packages("pwr") 
install.packages("simr")
install.packages("Publish")
install.packages("ggpubr")
install.packages("emmeans")
```

```{r, message=FALSE}
library("reshape") # variety of methods for reshaping data prior 
library("janitor") # for cleaning variable names 
library("DT") # for nice tables
library("Hmisc") # for smean function for bootstrapped confidence intervals 
library("tidyverse") # for data wrangling, visualization, etc. 
library("lme4") # for fitting and analyzing mixed models
library("MuMIn") # for calculating effect sizes
library("pwr") #for power analysis 
library("simr") # for power analysis 
library("ggpubr") # for publication Ready Plots
library("emmeans") # for post hoc tests
```

```{r}
# set ggplot theme 
theme_set(
  theme_classic()
)
```

## Experiment 1:

```{r}
###Pilot 1
#### Read in Data
df.responses <- read.csv(file = "explanation_selection_positive_outcome_study_2-responses.csv", stringsAsFactors = F, sep = ",") 
df.participants <- read.csv(file = "explanation_selection_positive_outcome_study_2-participants.csv", stringsAsFactors = F, sep = ",") 
#df.pilot2 <- merge(df.responses, df.participants, by="workerid")

```


```{r}
df.exp2 <- df.responses%>% 
  rename(explanation_disj_pos = explanation_response_1) %>% 
  rename(explanation_conj_pos = explanation_response_2) %>% 
  rename(intervention_disj_pos = intervention_response_1) %>% 
  rename(intervention_conj_pos = intervention_response_2) %>% 
  gather(condition, response, "explanation_disj_pos":"intervention_conj_pos") %>% 
 mutate(structure = case_when(
           str_detect(condition, "_conj") ~ "conjunctive_pos",
           str_detect(condition, "_disj") ~ "disjunctive_pos") )%>% 
  mutate(responsetype = case_when(
           str_detect(condition, "explanation_") ~ "explanation",
           str_detect(condition, "intervention") ~ "intervention")) %>% 
  mutate(response = recode (response, 
                            "orange" = "abnormal",
                            "blue" = "normal"))%>% 
  mutate(structure = factor(structure, levels=c("disjunctive_pos", "conjunctive_pos"))) %>% 
  mutate(responsetype = factor(responsetype, levels=c("intervention", "explanation")))

```

```{r}
FreqExp2<-ggplot(df.exp2, aes(x=response, group = structure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~structure)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14), 
  strip.text = element_text(color="black", size = 12))+
 facet_grid(structure~responsetype)
  

FreqExp2
```


```{r}
df.summary<-df.responses %>% 
  sum(explanation_response_1 == intervention_response_1)

sum(df.responses$explanation_response_1 == df.responses$intervention_response_1)
sum(df.responses$explanation_response_2 == df.responses$intervention_response_2)

sum(df.responses$intervention_response_1 == df.responses$intervention_response_2)
sum(df.responses$explanation_response_1 == df.responses$explanation_response_2)



```



