---
  title: "Explanation Valence Full Study"
author: "Lara Kirfel"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  bookdown::html_document2:
  toc: true
toc_depth: 4
theme: cosmo
highlight: tango
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")
```

# Install packages

```{r, message=FALSE}
install.packages("reshape")
install.packages("janitor")
install.packages("DT")
install.packages("Hmisc")
install.packages("broom")
install.packages("tidyverse")
install.packages("MuMIn")
install.packages("pwr") 
install.packages("simr")
install.packages("Publish")
install.packages("ggpubr")
install.packages("emmeans")
```

```{r, message=FALSE}
library("reshape") # variety of methods for reshaping data prior 
library("janitor") # for cleaning variable names 
library("DT") # for nice tables
library("Hmisc") # for smean function for bootstrapped confidence intervals 
library("tidyverse") # for data wrangling, visualization, etc. 
library("lme4") # for fitting and analyzing mixed models
library("MuMIn") # for calculating effect sizes
library("pwr") #for power analysis 
library("simr") # for power analysis 
library("ggpubr") # for publication Ready Plots
library("emmeans") # for post hoc tests
library("brms")        # for Bayesian regression modeling
library("tidybayes")   # for Bayesian regression modeling

```

```{r}
# set ggplot theme 
theme_set(
  theme_classic()
)
```

## Experiment 1: Read in Data

```{r}
###Study 1
#### Read in Data
df.responses = read.csv(file = "explanation_valence_full_study_1-responses.csv", stringsAsFactors = F, sep = ",") %>% 
      select(-error)


df.participants <- read.csv(file = "explanation_valence_full_study_1-participants.csv", stringsAsFactors = F, sep = ",") %>% 
    select(-c(proliferate.condition, error))


df.data1 <- merge(df.responses, df.participants, by="workerid")
```

## Experiment 1: Wrangle Data

```{r}
df.exp1 <- df.data1 %>% 
    gather("index", "response", -c(workerid, proliferate.condition, age, ethnicity, gender, feedback, race))%>% 
  mutate(CausalStructure  =
           case_when(
        proliferate.condition == "Condition 1" & index ==  "response_1"~ "Conjunctive",
        proliferate.condition == "Condition 1" & index ==  "response_2"~ "Disjunctive",
        proliferate.condition == "Condition 2" & index ==  "response_1"~ "Disjunctive",
        proliferate.condition == "Condition 2" & index ==  "response_2"~ "Conjunctive",
        proliferate.condition == "Condition 3" & index ==  "response_1"~ "Conjunctive",
        proliferate.condition == "Condition 3" & index ==  "response_2"~ "Disjunctive",
        proliferate.condition == "Condition 4" & index ==  "response_1"~ "Disjunctive",
        proliferate.condition == "Condition 4" & index ==  "response_2"~ "Conjunctive"))%>% 
  mutate(Outcome  =
           case_when(
        proliferate.condition == "Condition 1" & index ==  "response_1"~ "Positive",
        proliferate.condition == "Condition 1" & index ==  "response_2"~ "Positive",
        proliferate.condition == "Condition 2" & index ==  "response_1"~ "Positive",
        proliferate.condition == "Condition 2" & index ==  "response_2"~ "Positive",
        proliferate.condition == "Condition 3" & index ==  "response_1"~ "Negative",
        proliferate.condition == "Condition 3" & index ==  "response_2"~ "Negative",
        proliferate.condition == "Condition 4" & index ==  "response_1"~ "Negative",
        proliferate.condition == "Condition 4" & index ==  "response_2"~ "Negative")) %>% 
  mutate(Outcome= factor(Outcome, levels=c("Positive", "Negative"))) %>% 
  mutate(CausalStructure= factor(CausalStructure, levels=c("Conjunctive", "Disjunctive"))) %>%
  mutate(response = recode (response, 
                               "orange" = "abnormal",
                               "blue" = "normal" )) %>% 
  mutate(abnormal_selection =
           case_when(
        response == "abnormal" ~ "abnormal",
        response != "abnormal"~ "other")) %>% 
  mutate(normal_selection =
           case_when(
        response == "normal" ~ "normal",
        response != "normal"~ "other")) %>% 
  mutate(nopreference_selection =
           case_when(
        response == "no preference" ~ "no preference",
        response != "no preference"~ "other"))
```


### Analyses

# Contrasts
```{r}
contrasts(df.exp1$CausalStructure) = contr.sum(2)
contrasts(df.exp1$Outcome) = contr.sum(2)

```

# Abnormal Selection
```{r}
##################### Analysis
install.packages("ggeffects")
library("ggeffects")   # for marginal effects 

fit_abnormal_selection = brm(formula = abnormal_selection ~ CausalStructure * Outcome + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp1 %>% 
                              mutate(abnormal_selection = ifelse(abnormal_selection == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_abnormal_selection

fit_abnormal_selection %>% 
  ggpredict(terms = c("CausalStructure", "Outcome"))


FreqAbnormal<-ggplot(df.exp1, aes(x=abnormal_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqAbnormal
ggsave(FreqAbnormal, file="FreqAbnormal.png", dpi=400, height = 5, width = 8)

```
# Normal Selection
```{r}
##################### Analysis

fit_normal_selection = brm(formula = normal_selection ~ CausalStructure * Outcome + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp1 %>% 
                              mutate(normal_selection = ifelse(normal_selection == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_normal_selection


FreqNormal<-ggplot(df.exp1, aes(x=normal_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqNormal
ggsave(FreqNormal, file="FreqNormal.png", dpi=400, height = 5, width = 8)

```

# No preference Selection
```{r}
##################### Analysis

fit_nopreference_selection = brm(formula = nopreference_selection ~ CausalStructure * Outcome + (1 | workerid),
                              family = "bernoulli",
                              data = df.exp1 %>% 
                              mutate(nopreference_selection = ifelse(nopreference_selection == "other", 0, 1)),
                              seed = 1,
                              cores = 2)

fit_nopreference_selection


FreqNopreference<-ggplot(df.exp1, aes(x=nopreference_selection, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqNopreference
ggsave(FreqNopreference, file="FreqNopreference.png", dpi=400, height = 5, width = 8)

```



## Plotting Explanation Selections

```{r}
FreqExp1<-ggplot(df.exp1, aes(x=response, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqExp1

plot(FreqExp1)
ggsave(FreqExp1, file="FreqExp1.png", dpi=400, height = 5, width = 8)
```

### SUBSET

```{r}
df.exp1_subset <- df.exp1 %>% 
  filter(index=="response_2") 


FreqExp1_sub<-ggplot(df.exp1_subset, aes(x=response, group = CausalStructure))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~CausalStructure + Outcome)+
  theme_bw()+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14),
  strip.text.x = element_text(color="black", size = 14))

FreqExp1_sub

plot(FreqExp1_sub)
ggsave(FreqExp1_sub, file="FreqExp1_sub.png", dpi=400, height = 5, width = 8)
```
```{r}
df.data.1_subset <- df.data1 %>% 
  filter(response_1==response_2) 
```

```{r}
## summary statistics 
df.summary<-df.responses %>% 
  group_by() %>% 
  sum(explanation == intervention)

sum(df.responses$explanation_response_1 == df.responses$intervention_response_1)
sum(df.responses$explanation_response_2 == df.responses$intervention_response_2)



```

